// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addAccountMember = `-- name: AddAccountMember :exec
INSERT INTO account_members (account_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddAccountMemberParams struct {
	AccountID uuid.UUID `json:"account_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddAccountMember(ctx context.Context, arg AddAccountMemberParams) error {
	_, err := q.db.Exec(ctx, addAccountMember, arg.AccountID, arg.UserID, arg.Role)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, owner_user_id)
VALUES ($1, $2)
RETURNING id, name, owner_user_id, plan, computer_limit, stripe_customer_id, subscription_status, grace_until, created_at
`

type CreateAccountParams struct {
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.OwnerUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Plan,
		&i.ComputerLimit,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.GraceUntil,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, email_verified_at, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountMembership = `-- name: GetAccountMembership :one
SELECT role FROM account_members
WHERE account_id = $1 AND user_id = $2
`

type GetAccountMembershipParams struct {
	AccountID uuid.UUID `json:"account_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAccountMembership(ctx context.Context, arg GetAccountMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, getAccountMembership, arg.AccountID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, email_verified_at, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsForUser = `-- name: ListAccountsForUser :many
SELECT a.id, a.name, a.owner_user_id, a.plan, a.computer_limit, a.stripe_customer_id, a.subscription_status, a.grace_until, a.created_at FROM accounts a
JOIN account_members m ON m.account_id = a.id
WHERE m.user_id = $1
ORDER BY a.created_at
`

func (q *Queries) ListAccountsForUser(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.Plan,
			&i.ComputerLimit,
			&i.StripeCustomerID,
			&i.SubscriptionStatus,
			&i.GraceUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
