// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountMember = `-- name: AddAccountMember :exec
INSERT INTO account_members (account_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddAccountMemberParams struct {
	AccountID uuid.UUID `json:"account_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddAccountMember(ctx context.Context, arg AddAccountMemberParams) error {
	_, err := q.db.Exec(ctx, addAccountMember, arg.AccountID, arg.UserID, arg.Role)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, owner_user_id)
VALUES ($1, $2)
RETURNING id, name, owner_user_id, plan, computer_limit, stripe_customer_id, subscription_status, grace_until, created_at
`

type CreateAccountParams struct {
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.OwnerUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Plan,
		&i.ComputerLimit,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.GraceUntil,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, email_verified_at, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"-"`
	Name         string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccountMember = `-- name: DeleteAccountMember :execrows
DELETE FROM account_members WHERE user_id = $1 AND role <> 'owner'
`

// The owner row is deliberately unreachable here: an account with no owner has
// nobody who can be billed or delete it, and ownership is not transferable in
// v1 (see specs/2026-09-05-saas-design.md).
func (q *Queries) DeleteAccountMember(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountMember, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, owner_user_id, plan, computer_limit, stripe_customer_id, subscription_status, grace_until, created_at FROM accounts WHERE id = $1
`

// The caller's own account row. RLS scopes it: called inside inAccount, it can
// only ever return the account the scope names.
func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.Plan,
		&i.ComputerLimit,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.GraceUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, email_verified_at, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountMembers = `-- name: ListAccountMembers :many
SELECT u.id, u.email, u.name, m.role, m.created_at
FROM account_members m
JOIN users u ON u.id = m.user_id
ORDER BY CASE m.role WHEN 'owner' THEN 0 ELSE 1 END, u.email
`

type ListAccountMembersRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAccountMembers(ctx context.Context) ([]ListAccountMembersRow, error) {
	rows, err := q.db.Query(ctx, listAccountMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountMembersRow
	for rows.Next() {
		var i ListAccountMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
