// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: applications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRoomApplication = `-- name: AddRoomApplication :one
INSERT INTO applications (account_id, room_id, name, list)
VALUES ($1, $2, $3, $4)
ON CONFLICT (room_id, name, list) DO UPDATE SET enabled = true
RETURNING id, account_id, room_id, name, list, enabled, created_at
`

type AddRoomApplicationParams struct {
	AccountID uuid.UUID `json:"account_id"`
	RoomID    uuid.UUID `json:"room_id"`
	Name      string    `json:"name"`
	List      string    `json:"list"`
}

func (q *Queries) AddRoomApplication(ctx context.Context, arg AddRoomApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, addRoomApplication,
		arg.AccountID,
		arg.RoomID,
		arg.Name,
		arg.List,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RoomID,
		&i.Name,
		&i.List,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoomApplication = `-- name: DeleteRoomApplication :execrows
DELETE FROM applications WHERE id = $1 AND room_id = $2
`

type DeleteRoomApplicationParams struct {
	ID     uuid.UUID `json:"id"`
	RoomID uuid.UUID `json:"room_id"`
}

func (q *Queries) DeleteRoomApplication(ctx context.Context, arg DeleteRoomApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoomApplication, arg.ID, arg.RoomID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRoomApplications = `-- name: ListRoomApplications :many
SELECT id, account_id, room_id, name, list, enabled, created_at FROM applications WHERE room_id = $1 ORDER BY name
`

func (q *Queries) ListRoomApplications(ctx context.Context, roomID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listRoomApplications, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RoomID,
			&i.Name,
			&i.List,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
