// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: binding_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBindingToken = `-- name: CreateBindingToken :one
INSERT INTO binding_tokens (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, created_at, expires_at, revoked_at
`

type CreateBindingTokenParams struct {
	AccountID uuid.UUID          `json:"account_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateBindingToken(ctx context.Context, arg CreateBindingTokenParams) (BindingToken, error) {
	row := q.db.QueryRow(ctx, createBindingToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i BindingToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveBindingToken = `-- name: GetActiveBindingToken :one
SELECT id, account_id, token_hash, created_at, expires_at, revoked_at FROM binding_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActiveBindingToken(ctx context.Context, tokenHash string) (BindingToken, error) {
	row := q.db.QueryRow(ctx, getActiveBindingToken, tokenHash)
	var i BindingToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
