// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: computers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countComputers = `-- name: CountComputers :one
SELECT count(*) FROM computers
`

func (q *Queries) CountComputers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countComputers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getComputer = `-- name: GetComputer :one
SELECT id, account_id, room_id, display_name, machine_guid, hostname, os_name, os_build, arch, agent_version, hardware, runtime, token_hash, blocked, enrolled_at, last_seen_at FROM computers WHERE id = $1
`

func (q *Queries) GetComputer(ctx context.Context, id uuid.UUID) (Computer, error) {
	row := q.db.QueryRow(ctx, getComputer, id)
	var i Computer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RoomID,
		&i.DisplayName,
		&i.MachineGuid,
		&i.Hostname,
		&i.OsName,
		&i.OsBuild,
		&i.Arch,
		&i.AgentVersion,
		&i.Hardware,
		&i.Runtime,
		&i.TokenHash,
		&i.Blocked,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listComputers = `-- name: ListComputers :many
SELECT id, account_id, room_id, display_name, machine_guid, hostname, os_name, os_build, arch, agent_version, hardware, runtime, token_hash, blocked, enrolled_at, last_seen_at FROM computers ORDER BY COALESCE(NULLIF(display_name, ''), hostname)
`

func (q *Queries) ListComputers(ctx context.Context) ([]Computer, error) {
	rows, err := q.db.Query(ctx, listComputers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Computer
	for rows.Next() {
		var i Computer
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RoomID,
			&i.DisplayName,
			&i.MachineGuid,
			&i.Hostname,
			&i.OsName,
			&i.OsBuild,
			&i.Arch,
			&i.AgentVersion,
			&i.Hardware,
			&i.Runtime,
			&i.TokenHash,
			&i.Blocked,
			&i.EnrolledAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComputer = `-- name: UpdateComputer :one
UPDATE computers SET
    display_name = COALESCE($1, display_name),
    room_id      = CASE WHEN $2::boolean
                        THEN $3 ELSE room_id END,
    blocked      = COALESCE($4, blocked)
WHERE id = $5
RETURNING id, account_id, room_id, display_name, machine_guid, hostname, os_name, os_build, arch, agent_version, hardware, runtime, token_hash, blocked, enrolled_at, last_seen_at
`

type UpdateComputerParams struct {
	DisplayName *string    `json:"display_name"`
	SetRoom     bool       `json:"set_room"`
	RoomID      *uuid.UUID `json:"room_id"`
	Blocked     *bool      `json:"blocked"`
	ID          uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateComputer(ctx context.Context, arg UpdateComputerParams) (Computer, error) {
	row := q.db.QueryRow(ctx, updateComputer,
		arg.DisplayName,
		arg.SetRoom,
		arg.RoomID,
		arg.Blocked,
		arg.ID,
	)
	var i Computer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RoomID,
		&i.DisplayName,
		&i.MachineGuid,
		&i.Hostname,
		&i.OsName,
		&i.OsBuild,
		&i.Arch,
		&i.AgentVersion,
		&i.Hardware,
		&i.Runtime,
		&i.TokenHash,
		&i.Blocked,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertComputerByGUID = `-- name: UpsertComputerByGUID :one
INSERT INTO computers (
    account_id, machine_guid, hostname, os_name, os_build, arch,
    agent_version, hardware, token_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7, COALESCE($9, '{}'::jsonb), $8)
ON CONFLICT (account_id, machine_guid) DO UPDATE SET
    hostname      = EXCLUDED.hostname,
    os_name       = EXCLUDED.os_name,
    os_build      = EXCLUDED.os_build,
    arch          = EXCLUDED.arch,
    agent_version = EXCLUDED.agent_version,
    hardware      = EXCLUDED.hardware,
    token_hash    = EXCLUDED.token_hash,
    enrolled_at   = now()
RETURNING id, account_id, room_id, display_name, machine_guid, hostname, os_name, os_build, arch, agent_version, hardware, runtime, token_hash, blocked, enrolled_at, last_seen_at
`

type UpsertComputerByGUIDParams struct {
	AccountID    uuid.UUID   `json:"account_id"`
	MachineGuid  string      `json:"machine_guid"`
	Hostname     string      `json:"hostname"`
	OsName       string      `json:"os_name"`
	OsBuild      string      `json:"os_build"`
	Arch         string      `json:"arch"`
	AgentVersion string      `json:"agent_version"`
	TokenHash    string      `json:"token_hash"`
	Hardware     interface{} `json:"hardware"`
}

// Reinstalling an agent on a known machine updates the row and rotates its
// token instead of adding a duplicate to the pool.
func (q *Queries) UpsertComputerByGUID(ctx context.Context, arg UpsertComputerByGUIDParams) (Computer, error) {
	row := q.db.QueryRow(ctx, upsertComputerByGUID,
		arg.AccountID,
		arg.MachineGuid,
		arg.Hostname,
		arg.OsName,
		arg.OsBuild,
		arg.Arch,
		arg.AgentVersion,
		arg.TokenHash,
		arg.Hardware,
	)
	var i Computer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RoomID,
		&i.DisplayName,
		&i.MachineGuid,
		&i.Hostname,
		&i.OsName,
		&i.OsBuild,
		&i.Arch,
		&i.AgentVersion,
		&i.Hardware,
		&i.Runtime,
		&i.TokenHash,
		&i.Blocked,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}
