// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: email_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :one
UPDATE email_tokens SET used_at = now()
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
RETURNING user_id, email
`

type ConsumeEmailTokenParams struct {
	TokenHash string `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

type ConsumeEmailTokenRow struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
}

// Marks the token used and returns it, in one statement. Two statements would
// be a race: two clicks on the same link, milliseconds apart, would both find
// it unused. The WHERE clause carries every condition, so a spent, expired or
// unknown token all return no rows and are answered identically.
func (q *Queries) ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (ConsumeEmailTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeEmailToken, arg.TokenHash, arg.Purpose)
	var i ConsumeEmailTokenRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_tokens (token_hash, user_id, purpose, email, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEmailTokenParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	Purpose   string             `json:"purpose"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}

const deleteEmailTokensFor = `-- name: DeleteEmailTokensFor :exec
DELETE FROM email_tokens WHERE user_id = $1 AND purpose = $2
`

type DeleteEmailTokensForParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Purpose string    `json:"purpose"`
}

// Minting supersedes: a fresh link invalidates the previous one, so a mailbox
// never holds two working links to the same door.
func (q *Queries) DeleteEmailTokensFor(ctx context.Context, arg DeleteEmailTokensForParams) error {
	_, err := q.db.Exec(ctx, deleteEmailTokensFor, arg.UserID, arg.Purpose)
	return err
}

const deleteOtherSessionsForUser = `-- name: DeleteOtherSessionsForUser :execrows
DELETE FROM sessions WHERE user_id = $1 AND token_hash <> $2
`

type DeleteOtherSessionsForUserParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
}

// Every session except the one asking, for a password change from inside the
// cabinet: the person doing it should not be signed out by their own action.
func (q *Queries) DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessionsForUser, arg.UserID, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :execrows
DELETE FROM sessions WHERE user_id = $1
`

// Every session, for a completed reset.
func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, email_verified_at, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE users SET email_verified_at = now()
WHERE id = $1 AND email = $2 AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

// Only when the address still matches the one the link was sent to, and only
// when it is not already verified.
func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailVerified, arg.ID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredEmailTokens = `-- name: PurgeExpiredEmailTokens :execrows
DELETE FROM email_tokens WHERE expires_at < now() - interval '1 day'
`

// Spent or expired, plus a day of grace so a "my link says it is invalid"
// question can still be answered by looking.
func (q *Queries) PurgeExpiredEmailTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredEmailTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPassword = `-- name: SetPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"-"`
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.ID, arg.PasswordHash)
	return err
}
