// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	OwnerUserID        uuid.UUID          `json:"owner_user_id"`
	Plan               string             `json:"plan"`
	ComputerLimit      int32              `json:"computer_limit"`
	StripeCustomerID   string             `json:"stripe_customer_id"`
	SubscriptionStatus string             `json:"subscription_status"`
	GraceUntil         pgtype.Timestamptz `json:"grace_until"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AccountMember struct {
	AccountID uuid.UUID          `json:"account_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Application struct {
	ID        uuid.UUID          `json:"id"`
	AccountID uuid.UUID          `json:"account_id"`
	RoomID    uuid.UUID          `json:"room_id"`
	Name      string             `json:"name"`
	List      string             `json:"list"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Computer struct {
	ID           uuid.UUID          `json:"id"`
	AccountID    uuid.UUID          `json:"account_id"`
	RoomID       *uuid.UUID         `json:"room_id"`
	DisplayName  string             `json:"display_name"`
	MachineGuid  string             `json:"machine_guid"`
	Hostname     string             `json:"hostname"`
	OsName       string             `json:"os_name"`
	OsBuild      string             `json:"os_build"`
	Arch         string             `json:"arch"`
	AgentVersion string             `json:"agent_version"`
	Hardware     []byte             `json:"hardware"`
	Runtime      []byte             `json:"runtime"`
	TokenHash    string             `json:"-"`
	Blocked      bool               `json:"blocked"`
	EnrolledAt   pgtype.Timestamptz `json:"enrolled_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
}

type Room struct {
	ID                uuid.UUID          `json:"id"`
	AccountID         uuid.UUID          `json:"account_id"`
	Name              string             `json:"name"`
	Mode              string             `json:"mode"`
	ProtectionEnabled bool               `json:"protection_enabled"`
	PowerAllowed      bool               `json:"power_allowed"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	RoomID    uuid.UUID          `json:"room_id"`
	AccountID uuid.UUID          `json:"account_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	TokenHash  string             `json:"token_hash"`
	UserID     uuid.UUID          `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	Ip         string             `json:"ip"`
	UserAgent  string             `json:"user_agent"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Name            string             `json:"name"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
