// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	OwnerUserID        uuid.UUID          `json:"owner_user_id"`
	Plan               string             `json:"plan"`
	ComputerLimit      int32              `json:"computer_limit"`
	StripeCustomerID   string             `json:"stripe_customer_id"`
	SubscriptionStatus string             `json:"subscription_status"`
	GraceUntil         pgtype.Timestamptz `json:"grace_until"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AccountMember struct {
	AccountID uuid.UUID          `json:"account_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Name            string             `json:"name"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
