// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: process_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listComputerProcessEvents = `-- name: ListComputerProcessEvents :many
SELECT pe.id, pe.computer_id, pe.room_id, pe.process, pe.reason, pe.count,
       pe.first_at, pe.last_at, pe.created_at,
       COALESCE(NULLIF(c.display_name, ''), c.hostname)::text AS computer_name
FROM process_events pe
JOIN computers c ON c.id = pe.computer_id
WHERE pe.computer_id = $1::uuid
  AND ($2::text     IS NULL OR pe.process = $2::text)
  AND ($3::text      IS NULL OR pe.reason  = $3::text)
  AND ($4::timestamptz IS NULL OR pe.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR pe.created_at <= $5::timestamptz)
  AND ($6::timestamptz IS NULL
       OR (pe.created_at, pe.id) < ($6::timestamptz, $7::uuid))
ORDER BY pe.created_at DESC, pe.id DESC
LIMIT $8
`

type ListComputerProcessEventsParams struct {
	ComputerID uuid.UUID          `json:"computer_id"`
	Process    *string            `json:"process"`
	Reason     *string            `json:"reason"`
	Since      pgtype.Timestamptz `json:"since"`
	Until      pgtype.Timestamptz `json:"until"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   *uuid.UUID         `json:"before_id"`
	RowLimit   int32              `json:"row_limit"`
}

type ListComputerProcessEventsRow struct {
	ID           uuid.UUID          `json:"id"`
	ComputerID   uuid.UUID          `json:"computer_id"`
	RoomID       *uuid.UUID         `json:"room_id"`
	Process      string             `json:"process"`
	Reason       string             `json:"reason"`
	Count        int32              `json:"count"`
	FirstAt      pgtype.Timestamptz `json:"first_at"`
	LastAt       pgtype.Timestamptz `json:"last_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ComputerName string             `json:"computer_name"`
}

// Its own statement rather than the room query with a computer filter: a
// machine in no room has room_id NULL on every row, and the room query can
// never match it.
func (q *Queries) ListComputerProcessEvents(ctx context.Context, arg ListComputerProcessEventsParams) ([]ListComputerProcessEventsRow, error) {
	rows, err := q.db.Query(ctx, listComputerProcessEvents,
		arg.ComputerID,
		arg.Process,
		arg.Reason,
		arg.Since,
		arg.Until,
		arg.BeforeTime,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComputerProcessEventsRow
	for rows.Next() {
		var i ListComputerProcessEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ComputerID,
			&i.RoomID,
			&i.Process,
			&i.Reason,
			&i.Count,
			&i.FirstAt,
			&i.LastAt,
			&i.CreatedAt,
			&i.ComputerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomProcessEvents = `-- name: ListRoomProcessEvents :many
SELECT pe.id, pe.computer_id, pe.room_id, pe.process, pe.reason, pe.count,
       pe.first_at, pe.last_at, pe.created_at,
       COALESCE(NULLIF(c.display_name, ''), c.hostname)::text AS computer_name
FROM process_events pe
JOIN computers c ON c.id = pe.computer_id
WHERE pe.room_id = $1::uuid
  AND ($2::text     IS NULL OR pe.process     = $2::text)
  AND ($3::text      IS NULL OR pe.reason      = $3::text)
  AND ($4::uuid    IS NULL OR pe.computer_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR pe.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR pe.created_at <= $6::timestamptz)
  AND ($7::timestamptz IS NULL
       OR (pe.created_at, pe.id) < ($7::timestamptz, $8::uuid))
ORDER BY pe.created_at DESC, pe.id DESC
LIMIT $9
`

type ListRoomProcessEventsParams struct {
	RoomID     uuid.UUID          `json:"room_id"`
	Process    *string            `json:"process"`
	Reason     *string            `json:"reason"`
	Computer   *uuid.UUID         `json:"computer"`
	Since      pgtype.Timestamptz `json:"since"`
	Until      pgtype.Timestamptz `json:"until"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
	BeforeID   *uuid.UUID         `json:"before_id"`
	RowLimit   int32              `json:"row_limit"`
}

type ListRoomProcessEventsRow struct {
	ID           uuid.UUID          `json:"id"`
	ComputerID   uuid.UUID          `json:"computer_id"`
	RoomID       *uuid.UUID         `json:"room_id"`
	Process      string             `json:"process"`
	Reason       string             `json:"reason"`
	Count        int32              `json:"count"`
	FirstAt      pgtype.Timestamptz `json:"first_at"`
	LastAt       pgtype.Timestamptz `json:"last_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ComputerName string             `json:"computer_name"`
}

// One query rather than a family of them: five optional filters would
// otherwise be thirty-two statements. Each filter is inert when its argument
// is NULL. The cursor is the same (created_at, id) row comparison the events
// feed uses -- keyed on the pair rather than an offset, because rows arrive
// while somebody is paging and OFFSET would silently repeat or skip them.
func (q *Queries) ListRoomProcessEvents(ctx context.Context, arg ListRoomProcessEventsParams) ([]ListRoomProcessEventsRow, error) {
	rows, err := q.db.Query(ctx, listRoomProcessEvents,
		arg.RoomID,
		arg.Process,
		arg.Reason,
		arg.Computer,
		arg.Since,
		arg.Until,
		arg.BeforeTime,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomProcessEventsRow
	for rows.Next() {
		var i ListRoomProcessEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ComputerID,
			&i.RoomID,
			&i.Process,
			&i.Reason,
			&i.Count,
			&i.FirstAt,
			&i.LastAt,
			&i.CreatedAt,
			&i.ComputerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProcessEvent = `-- name: RecordProcessEvent :exec
INSERT INTO process_events
    (account_id, computer_id, room_id, process, reason, count, first_at, last_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordProcessEventParams struct {
	AccountID  uuid.UUID          `json:"account_id"`
	ComputerID uuid.UUID          `json:"computer_id"`
	RoomID     *uuid.UUID         `json:"room_id"`
	Process    string             `json:"process"`
	Reason     string             `json:"reason"`
	Count      int32              `json:"count"`
	FirstAt    pgtype.Timestamptz `json:"first_at"`
	LastAt     pgtype.Timestamptz `json:"last_at"`
}

func (q *Queries) RecordProcessEvent(ctx context.Context, arg RecordProcessEventParams) error {
	_, err := q.db.Exec(ctx, recordProcessEvent,
		arg.AccountID,
		arg.ComputerID,
		arg.RoomID,
		arg.Process,
		arg.Reason,
		arg.Count,
		arg.FirstAt,
		arg.LastAt,
	)
	return err
}

const setLastEventBatch = `-- name: SetLastEventBatch :exec
UPDATE computers SET last_event_batch = $2 WHERE id = $1
`

type SetLastEventBatchParams struct {
	ID             uuid.UUID `json:"id"`
	LastEventBatch *string   `json:"last_event_batch"`
}

// Stamped in the same transaction as the batch it acknowledges, so a partially
// recorded batch cannot exist.
func (q *Queries) SetLastEventBatch(ctx context.Context, arg SetLastEventBatchParams) error {
	_, err := q.db.Exec(ctx, setLastEventBatch, arg.ID, arg.LastEventBatch)
	return err
}
