// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (account_id, name) VALUES ($1, $2) RETURNING id, account_id, name, mode, protection_enabled, power_allowed, created_at
`

type CreateRoomParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.AccountID, arg.Name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Mode,
		&i.ProtectionEnabled,
		&i.PowerAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :execrows
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoom, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoom = `-- name: GetRoom :one
SELECT id, account_id, name, mode, protection_enabled, power_allowed, created_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Mode,
		&i.ProtectionEnabled,
		&i.PowerAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, account_id, name, mode, protection_enabled, power_allowed, created_at FROM rooms ORDER BY created_at
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Mode,
			&i.ProtectionEnabled,
			&i.PowerAllowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms SET
    name               = COALESCE($1, name),
    mode               = COALESCE($2, mode),
    protection_enabled = COALESCE($3, protection_enabled),
    power_allowed      = COALESCE($4, power_allowed)
WHERE id = $5
RETURNING id, account_id, name, mode, protection_enabled, power_allowed, created_at
`

type UpdateRoomParams struct {
	Name              *string   `json:"name"`
	Mode              *string   `json:"mode"`
	ProtectionEnabled *bool     `json:"protection_enabled"`
	PowerAllowed      *bool     `json:"power_allowed"`
	ID                uuid.UUID `json:"id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.Name,
		arg.Mode,
		arg.ProtectionEnabled,
		arg.PowerAllowed,
		arg.ID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Mode,
		&i.ProtectionEnabled,
		&i.PowerAllowed,
		&i.CreatedAt,
	)
	return i, err
}
