// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: room_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, account_id, user_id, role)
VALUES ($1, $2, $3, 'member')
ON CONFLICT (room_id, user_id) DO NOTHING
`

type AddRoomMemberParams struct {
	RoomID    uuid.UUID `json:"room_id"`
	AccountID uuid.UUID `json:"account_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember, arg.RoomID, arg.AccountID, arg.UserID)
	return err
}

const deleteRoomMember = `-- name: DeleteRoomMember :execrows
DELETE FROM room_members WHERE room_id = $1 AND user_id = $2
`

type DeleteRoomMemberParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRoomMember(ctx context.Context, arg DeleteRoomMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoomMember, arg.RoomID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComputerForMember = `-- name: GetComputerForMember :one
SELECT c.id, c.account_id, c.room_id, c.display_name, c.machine_guid, c.hostname, c.os_name, c.os_build, c.arch, c.agent_version, c.hardware, c.runtime, c.token_hash, c.blocked, c.enrolled_at, c.last_seen_at FROM computers c
JOIN room_members rm ON rm.room_id = c.room_id
WHERE c.id = $1 AND rm.user_id = $2
`

type GetComputerForMemberParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetComputerForMember(ctx context.Context, arg GetComputerForMemberParams) (Computer, error) {
	row := q.db.QueryRow(ctx, getComputerForMember, arg.ID, arg.UserID)
	var i Computer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RoomID,
		&i.DisplayName,
		&i.MachineGuid,
		&i.Hostname,
		&i.OsName,
		&i.OsBuild,
		&i.Arch,
		&i.AgentVersion,
		&i.Hardware,
		&i.Runtime,
		&i.TokenHash,
		&i.Blocked,
		&i.EnrolledAt,
		&i.LastSeenAt,
	)
	return i, err
}

const isRoomMember = `-- name: IsRoomMember :one
SELECT EXISTS (SELECT 1 FROM room_members WHERE room_id = $1 AND user_id = $2)
`

type IsRoomMemberParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRoomMember, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAccessibleAccounts = `-- name: ListAccessibleAccounts :many
SELECT ranked.account_id, ranked.role, ranked.account_name FROM (
    SELECT DISTINCT ON (accessible.account_id)
           accessible.account_id AS account_id,
           accessible.role       AS role,
           a.name                AS account_name
    FROM (
        SELECT m.account_id AS account_id, m.role AS role
        FROM account_members m WHERE m.user_id = $1
        UNION
        SELECT rm.account_id AS account_id, 'member'::text AS role
        FROM room_members rm WHERE rm.user_id = $1
    ) accessible
    JOIN accounts a ON a.id = accessible.account_id
    ORDER BY accessible.account_id,
             CASE accessible.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END
) ranked
ORDER BY CASE ranked.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,
         ranked.account_name
`

type ListAccessibleAccountsRow struct {
	AccountID   uuid.UUID `json:"account_id"`
	Role        string    `json:"role"`
	AccountName string    `json:"account_name"`
}

// Account membership and room grants both lead to an account. The strongest
// role wins, so a user who is an admin and also a room member is an admin —
// and DISTINCT ON is what makes that true in the result as well as in
// intention: the UNION yields one row per PATH, so without it such a user saw
// the same account listed twice, once per role, and an account switcher would
// draw it twice.
//
// The name comes from accounts, readable here without an account scope by the
// pre-scope policy migration 00015 widened for exactly this query. The outer
// ORDER BY keeps owner first, which is the default SessionAuth picks when the
// caller names no account.
func (q *Queries) ListAccessibleAccounts(ctx context.Context, userID uuid.UUID) ([]ListAccessibleAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleAccountsRow
	for rows.Next() {
		var i ListAccessibleAccountsRow
		if err := rows.Scan(&i.AccountID, &i.Role, &i.AccountName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComputersForMember = `-- name: ListComputersForMember :many
SELECT c.id, c.account_id, c.room_id, c.display_name, c.machine_guid, c.hostname, c.os_name, c.os_build, c.arch, c.agent_version, c.hardware, c.runtime, c.token_hash, c.blocked, c.enrolled_at, c.last_seen_at FROM computers c
JOIN room_members rm ON rm.room_id = c.room_id
WHERE rm.user_id = $1
ORDER BY COALESCE(NULLIF(c.display_name, ''), c.hostname)
`

func (q *Queries) ListComputersForMember(ctx context.Context, userID uuid.UUID) ([]Computer, error) {
	rows, err := q.db.Query(ctx, listComputersForMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Computer
	for rows.Next() {
		var i Computer
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RoomID,
			&i.DisplayName,
			&i.MachineGuid,
			&i.Hostname,
			&i.OsName,
			&i.OsBuild,
			&i.Arch,
			&i.AgentVersion,
			&i.Hardware,
			&i.Runtime,
			&i.TokenHash,
			&i.Blocked,
			&i.EnrolledAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT u.id, u.email, u.name FROM room_members rm
JOIN users u ON u.id = rm.user_id
WHERE rm.room_id = $1
ORDER BY u.email
`

type ListRoomMembersRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
}

func (q *Queries) ListRoomMembers(ctx context.Context, roomID uuid.UUID) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMembersRow
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsForMember = `-- name: ListRoomsForMember :many
SELECT r.id, r.account_id, r.name, r.mode, r.protection_enabled, r.power_allowed, r.created_at FROM rooms r
JOIN room_members rm ON rm.room_id = r.id
WHERE rm.user_id = $1
ORDER BY r.created_at
`

func (q *Queries) ListRoomsForMember(ctx context.Context, userID uuid.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsForMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Mode,
			&i.ProtectionEnabled,
			&i.PowerAllowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
