// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Ip        string             `json:"ip"`
	UserAgent string             `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - interval '1 day'
`

// Expired rows are already unusable (GetSession filters on expires_at), so
// this is housekeeping, not security: without it the table only grows. The
// day of grace keeps a row around long enough to be visible in a "your
// session expired" investigation.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, user_id, created_at, expires_at, last_used_at, ip, user_agent FROM sessions WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET
    last_used_at = now(),
    expires_at   = LEAST($1::timestamptz, created_at + interval '1 year')
WHERE token_hash = $2 AND last_used_at < now() - interval '1 hour'
`

type TouchSessionParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	TokenHash string             `json:"token_hash"`
}

// Sliding renewal, self-throttled, under an absolute ceiling.
//
// Renewing on every authenticated request turns every GET into a write: WAL
// traffic proportional to all API traffic, and a row lock that serialises
// concurrent requests sharing one session. At a 30-day TTL, renewing at most
// hourly is indistinguishable to the user.
//
// LEAST(..., created_at + 1 year) is the ceiling. Without it the renewal is
// unbounded: a session used once a week never expires, so a token stolen from
// a device that stays in use is good forever, and "sign out everywhere" is the
// only revocation that exists. A year is long enough that no parent is thrown
// out of the app by it and short enough that an abandoned token dies.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.TokenHash)
	return err
}
